import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by Henry Rivardo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased font-sans bg-[rgb(var(--bg))] text-[rgb(var(--fg))]">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
